baseURL = 'https://teampointbarre.fr/'
languageCode = 'fr-fr'
title = 'Team Point Barre'
theme = 'hugo-story'
copyright = "{year}"

[menu]
[[menu.main]]
  name = 'La méthode'
  url = '/methode/'
  weight = 10
[[menu.main]]
  name = 'La team'
  url = '/team/'
  weight = 20

[params]
    description = "Le sport outdoor comme outil de développement personnel. Trail, vélo sacoche et méthode Point Barre."
    joinForm = "https://docs.google.com/forms/d/e/1FAIpQLSc2YrVFK6XExGr0JUpWp3N02ZLj5yABxZw6445u5hinI7bjAw/viewform"

[Params.social]
  instagram = "https://instagram.com/teampointbarre"